# H2 DB ?? ? ?? ???
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 ??? DB? ?? ? ??? ??? ?? ???? ?? (?? 3? ??)
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# MyBatis ??
# SQL ??? ???? XML ???? ??? ?????.
mybatis.mapper-locations=classpath:mapper/*.xml
# Java ??? ?????(camelCase)? DB? ????(snake_case)? ???? ??????.
mybatis.configuration.map-underscore-to-camel-case=true